print('xxx.reporting.php.rubika.app.xnxx.com')
print('sexy.puren.gif.sexy.xxx.and.haker.hak.hak.rubika.yftt18k.haker.sexy.yftt15k')('Film.sexy.rubika.xxx.filtering')('/yftt14k')('Filtering')('*filter.xxx.rubika*')('/yftt13k')filtering((*rubika.filter.porn.film.sexy*)(Xxx.filtering.sex.rubika.filter)https://s8.uupload.ir/files/inshot_20230803_193609355_w26.jpg(Filter.rubika.xxx)(http://v.2.9.1.yftt15k.in)(http://v.3.8.9.yftt15k.in)(http://93.115.150.55')
print('python.xnxx.xxx.sxsi.photo.com')
http://radio-tacklorix.xlphp.net
